---
title: 'Introduction to Instrumental Variables'
description: 'This chapter will introduce you to Instrumental Variables (IV) analysis, a tricky but powerful method to find causality through indirect inference'
---

## Course Trailer for Causal Inference with R – Instrumental Variables & RDD

```yaml
type: VideoExercise
key: bf3c9abc64
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/306246988
```


---

## The Logic of Instrumental Variables

```yaml
type: VideoExercise
key: 9c7273586e
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/219558904
```


---

## Visual Logic of Instrumental Variables

```yaml
type: VideoExercise
key: 8a1c462927
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/219559011
```


---

## What is the Relationship Between the Instrument and the Outcome?

```yaml
type: PureMultipleChoiceExercise
key: 8c410956e7
lang: r
xp: 50
skills: 1
```

As the videos discussed, there are some strict requirements to use instrumental variables analysis, so we will review the relationship between the instrument and the outcome. Which one of these is the correct assumption for IV analysis?

`@hint`


`@possible_answers`
- The instrument has a direct causal effect on the outcome, but is only correlated with the treatment.
- The instrument has a direct causal effect on the treatment, but is only correlated with the outcome.
- The instrument has no direct causal effect on either the treatment or the outcome.
- The instrument has a direct causal effect on both the treatment and the outcome.

`@feedback`
msg1 = "That's not correct. The instrument should only be correlated with the outcome, and must have a causal effect on the treatment variable. Try again."
msg2 = "Correct! Nice job."
msg3 = "The instrument must have a causal effect on the treatment (but not on the outcome) to use an instrumental variables analysis. Try again."
msg4 = "The instrument should have a causal effect on the treatment, but should only be correlated wit the outcome. Try again."
test_mc(correct = 2, feedback_msgs = c(msg1,msg2,msg3,msg4))

---

## What is the Relationship Between the Instrument and the Treatment?

```yaml
type: PureMultipleChoiceExercise
key: 4c7896c749
lang: r
xp: 50
skills: 1
```

Now let us review the relationship between the instrument and the treatment.  Which one of these is the correct assumption for IV analysis?

`@hint`


`@possible_answers`
- The instrument is not correlated with the treatment.
- The treatment has a causal effect on the instrument.
- The treatment and the outcome have a causal effect on the instrument.
- The instrument has a causal effect on the treatment.

`@feedback`


---

## What is the Relationship Between the Instrument and the Other Pre-Treatment Variables?

```yaml
type: PureMultipleChoiceExercise
key: 8a1ad925e4
lang: r
xp: 50
skills: 1
```

The instrument is one of many variables that could be confounding the effect of what we really want to study: the effect of our treatment on the outcome. Let us review the relationship of the instrument to this larger pool of potential confounders. Which of the following statements is correct for an IV analysis?

`@hint`


`@possible_answers`
- The instrument must be correlated with all measured pre-treatment variables.
- The pre-treatment variables have a causal effect on the instrument.
- We do not need to worry about unobserved pre-treatment variables, they are by definition not correlated with the instrument.
- The instrument is uncorrelated with the other pre-treatment variables.

`@feedback`


---

## How Do We Calculate a Causal Effect with Instrumental Variables Analysis?

```yaml
type: PureMultipleChoiceExercise
key: ed73a92806
lang: r
xp: 50
skills: 1
```

So now we can summarize the main purpose of IV analysis. Once again, how does the instrumental variable help us understand the causal effect of the treatment on the outcome?

`@hint`


`@possible_answers`
- The treatment affects the instrument, which affects the outcome. The causal effect of the treatment on the outcome is equal to the correlation of the instrument and the treatment.
- The treatment affects the outcome, and the instrument is correlated with the outcome. To get the effect of the treatment on the outcome, we calculate the correlation of the instrument on the outcome.
- The instrument affects the treatment, and the treatment affects the outcome. To get the effect of the treatment on the outcome, we find the correlation of the instrument on the outcome, and subtract out the effect of the instrument on the treatment.
- The instrument and the treatment combine to create the outcome. So the treatment effect is the sum of the effect of the instrument on the treatment and the effect of the treatment on the outcome.

`@feedback`


---

## Some Instrumental Variables Terminology

```yaml
type: VideoExercise
key: 3ae8d65d96
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/219565557
```


---

## Is it Endogenous vs Exogenous Variation?

```yaml
type: PureMultipleChoiceExercise
key: 5ad3dddd73
lang: r
xp: 50
skills: 1
```

Suppose you are interested in the economic status of new college graduates, and have just gotten access to geographic data on where people live and work after they graduate from college. In your first step of data analysis, you subset this geographic data to categorize both their home and work locations as either urban or rural, giving you a binary treatment variable. Let's say that you then compare what kinds of places (rural vs. urban) where people live versus the kinds of places where they work. What kind of variation would that variable have?

`@hint`


`@possible_answers`
- Exogenous
- Endogenous
- Both

`@feedback`


---

## Instrumental Variables in Action: Education and Wages (graphs)

```yaml
type: VideoExercise
key: 953b93e528
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/219559159
```


---

## Instrumental Variables in Action: Education and Wages (tables)

```yaml
type: VideoExercise
key: 116a9fd6fa
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/219559305
```


---

## What if Our Data Shows No Clear Correlation Between Treatment and Outcome?

```yaml
type: PureMultipleChoiceExercise
key: e48c3917d8
lang: r
xp: 50
skills: 1
```

Suppose we run an Instrumental Variable analysis, and in our initial data exploration, we find that the treatment is uncorrelated with the outcome. But nonetheless, we carry on with the IV analysis and find that it shows a positive causal effect of the treatment on the outcome. How should we interpret these results?

`@hint`


`@possible_answers`
- One of the IV assumptions must be violated, thus the IV estimate is wrong.
- There could be a causal effect, but it must be small.
- There must be a large amount of measurement error in either the treatment or the instrument.
- None of the above.

`@feedback`


---

## The Three Instrumental Variables Assumptions

```yaml
type: VideoExercise
key: b70179796d
lang: r
xp: 50
skills: 1
video_link: //player.vimeo.com/video/219559447
```


---

## Alan the Egg Farmer Turns to Instrumental Variables

```yaml
type: PureMultipleChoiceExercise
key: 01af032fa2
lang: r
xp: 50
skills: 1
```

Alan the Egg Farmer consistently sells all of his fresh eggs on his island in the South Pacific. Since Alan is the only egg farmer on his island, he has no direct competition, and people seem to buy his eggs no matter what price he sets. Due to his great sales and lack of competition, Alan is considering greatly increasing the prices of his eggs. But how much do egg sales really vary when prices change? Alan wants to find out.

Luckily, he has a lot of down time and an interest in data science. He knows there are a lot of different factors involved in the production of eggs and in the sales of eggs, from chicken health to transportation costs to popular food trends, and he wants to find a single variable that can help him cut through the many possible confounding factors. So he comes up with an idea for doing an instrumental variable analysis: Alan knows that chickens produce fewer eggs in years with less rain, and he knows that farmers consistently increase their egg prices on years when they have low egg yields. Therefore, with a big dataset on egg sales and the weather history of nearby islands, Alan believes that he could study weather patterns as an instrument for egg prices, and he can use that instrument to find the impact of egg prices on egg sales. Which of the following assumptions does Alan's model depend on?
  
- A) Egg prices are affected only by the weather 
- B) The weather and amounts of egg sales are not both caused by another factor 
- C) The weather is not correlated with other factors (besides egg prices) that are consequential to egg sales
- D) The weather has no effect on egg sales

`@hint`


`@possible_answers`
- A, C
- B, D
- A, B, C 
- All of the above

`@feedback`
